spring.application.name=invex.bnpl

#spring.datasource.url=jdbc:sqlserver://SQLDEV2022.local.sahuayo.mx:1433;DatabaseName=SACS_Tultitlan;TrustServerCertificate=True;
#spring.datasource.username=acontreras
#spring.datasource.password=4Es6XW9gHmbM_Zrb


#spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.url=jdbc:h2:file:/data/demo
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

#spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.SQLServerDialect
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto= update

logging.file.name = invex.log
logging.file.path = /logs/invex
pring.output.ansi.enabled =ALWAYS